name: movie-prediction-serve
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flask=2.3.2
  - flask-cors=4.0.0
  - pandas=2.0.3
  - faiss-cpu=1.7.4
  - sentence-transformers=3.4.1
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - nltk=3.8.1
  - pip
  - pip:
      - transformers==4.49.0
      - huggingface_hub==0.29.2
